### ISSUE TITLE
[TODO] Criar guia de contribuição

### ISSUE THREAD

**Issue by darmsDD** [fga-eps-mds/2021.1-PC-GO1#3]
## Descrição
É necessário criar o guia de contribuição para este repositório. 

## Tarefas
- [x] Qual o formato dos commits
- [x] Qual o formato de pull requests
- [x] Como contribuir sendo membro externo

**Comment by bielrossi15** [comment]
Issue completa, guia de contribuicao criado
